## **Importing library**
- numpy(numerical python)is python library used for working with arrays 
- We have in Python a lists but they are slow to process.
 

In [158]:
import numpy as np 

#### **Creating An Array**

### **0-D**

In [159]:
arr0=np.array(45)
arr0

array(45)

In [160]:
type(arr0)

numpy.ndarray

In [161]:
arr0.dtype #data type

dtype('int32')

In [162]:
arr0.ndim #dimension

0

### **1-D**

In [163]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])

In [164]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [165]:
arr1.dtype

dtype('int32')

In [166]:
arr1.ndim

1

In [167]:
len(arr1)#how many items

10

In [168]:
arr1.size  # m :number of rows * n: number of columns  1*10=10


10

### **2-D(Matrix)**

In [169]:
arr2=np.array([[1,2,3,4],
               [5,6,7,8]]) 

In [170]:
arr2.dtype

dtype('int32')

In [171]:
arr2.ndim

2

In [172]:
len(arr2)# 2--->as this array contains two arrays(rows)

2

In [173]:
arr2.size  # m :number of rows * n: number of columns  2*4=8


8

### **3-D**

In [174]:
arr3=np.array([[[1,2,3,4],
               [5,6,7,8]],
               
               [[9,10,11,12],
                [13,14,15,16]]])

In [175]:
arr3.dtype

dtype('int32')

In [176]:
arr3.ndim

3

In [177]:
len(arr3)# 2--->as this array contains two arrays of arrays :)

2

In [178]:
arr3.size  # m :number of rows * n: number of columns * z   2*4*2=16


16

# **Array Indexing**
- Starting from zero don't forget

#### **1-Dimentional Array Traversing**

In [179]:
arr1[0]

1

In [180]:
for idx in range(len(arr1)):
    print(arr1[idx],end=" ")

1 2 3 4 5 6 7 8 9 10 

#### **2-Dimentional Array Traversing**

In [181]:
arr2[0] #return the first vector of values

array([1, 2, 3, 4])

In [182]:
arr2[0][0] #first value in first row 

1

In [183]:
arr2[0,0] #we can write it like this too

1

In [184]:
#traversing 
for i in range(len(arr2)):
    for j in range(len(arr2[i])):
        print(arr2[i][j], end=" ")

        

1 2 3 4 5 6 7 8 

#### **3-Dimentional Array Traversing**

In [185]:
arr3[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [186]:
arr3[0][0]

array([1, 2, 3, 4])

In [187]:
arr3[0][0][0]

1

In [188]:
for i in range(len(arr3)):
    for j in range(len(arr3[i])):
        for k in range(len(arr3[i][j])):
            print(arr3[i][j][k], end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

## **Slicing**
- process of extracting a subsequence of array
- Array[start:stop:step]
- start: The starting index of the slice (inclusive).
- stop: The ending index of the slice (exclusive).
- step (optional): The step or increment between elements



In [189]:
#Slicing with Positive Indices:
A = [0,1,2,3,4,5,6,7,8,9,10]
A[1:4]


[1, 2, 3]

In [190]:
#Negative Slicing(counting from the end)
A[-3:-1]

[8, 9]

In [191]:
#Take two steps so skip one and take one and so on
A[::2]

[0, 2, 4, 6, 8, 10]

In [192]:
# Reversed the Array 
A[::-1]  


[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [193]:
#give me all
A[:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [194]:
A[:5]   #first 5 items

[0, 1, 2, 3, 4]

In [195]:
A[5:]  #last five

[5, 6, 7, 8, 9, 10]

In [196]:
A[:5:-1] #negative slicing

[10, 9, 8, 7, 6]

In [197]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])



In [198]:
matrix[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [199]:
matrix[: ,1] #[rows ,column]

array([2, 5, 8])

In [200]:
matrix[:, ::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [202]:
new_matrix=matrix.copy()
new_matrix[:, 1] = 0
new_matrix

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])