## **Importing library**
- numpy(numerical python)is python library used for working with arrays 
- We have in Python a lists but they are slow to process.
 

In [1]:
import numpy as np 

#### **Creating An Array**

### **0-D**

In [2]:
arr0=np.array(45)
arr0

array(45)

In [3]:
type(arr0)

numpy.ndarray

In [4]:
arr0.dtype #data type

dtype('int32')

In [5]:
arr0.ndim #dimension

0

### **1-D**

In [6]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])

In [7]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr1.dtype

dtype('int32')

In [9]:
arr1.ndim

1

In [10]:
len(arr1)#how many items

10

In [11]:
arr1.size  # m :number of rows * n: number of columns  1*10=10


10

### **2-D(Matrix)**

In [12]:
arr2=np.array([[1,2,3,4],
               [5,6,7,8]]) 

In [13]:
arr2.dtype

dtype('int32')

In [14]:
arr2.ndim

2

In [15]:
len(arr2)# 2--->as this array contains two arrays(rows)

2

In [16]:
arr2.size  # m :number of rows * n: number of columns  2*4=8


8

### **3-D**

In [17]:
arr3=np.array([[[1,2,3,4],
               [5,6,7,8]],
               
               [[9,10,11,12],
                [13,14,15,16]]])

In [18]:
arr3.dtype

dtype('int32')

In [19]:
arr3.ndim

3

In [20]:
len(arr3)# 2--->as this array contains two arrays of arrays :)

2

In [21]:
arr3.size  # m :number of rows * n: number of columns * z   2*4*2=16


16

# **Array Indexing**
- Starting from zero don't forget

#### **1-Dimentional Array Traversing**

In [22]:
arr1[0]

1

In [23]:
for idx in range(len(arr1)):
    print(arr1[idx],end=" ")

1 2 3 4 5 6 7 8 9 10 

#### **2-Dimentional Array Traversing**

In [24]:
arr2[0] #return the first vector of values

array([1, 2, 3, 4])

In [25]:
arr2[0][0] #first value in first row 

1

In [26]:
arr2[0,0] #we can write it like this too

1

In [27]:
#traversing 
for i in range(len(arr2)):
    for j in range(len(arr2[i])):
        print(arr2[i][j], end=" ")

        

1 2 3 4 5 6 7 8 

#### **3-Dimentional Array Traversing**

In [28]:
arr3[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
arr3[0][0]

array([1, 2, 3, 4])

In [30]:
arr3[0][0][0]

1

In [31]:
for i in range(len(arr3)):
    for j in range(len(arr3[i])):
        for k in range(len(arr3[i][j])):
            print(arr3[i][j][k], end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

## **Slicing**
- process of extracting a subsequence of array
- Array[start:stop:step]
- start: The starting index of the slice (inclusive).
- stop: The ending index of the slice (exclusive).
- step (optional): The step or increment between elements



In [32]:
#Slicing with Positive Indices:
A = [0,1,2,3,4,5,6,7,8,9,10]
A[1:4]


[1, 2, 3]

In [33]:
#Negative Slicing(counting from the end)
A[-3:-1]

[8, 9]

In [34]:
#Take two steps so skip one and take one and so on
A[::2]

[0, 2, 4, 6, 8, 10]

In [35]:
# Reversed the Array 
A[::-1]  


[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [36]:
#give me all
A[:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [37]:
A[:5]   #first 5 items

[0, 1, 2, 3, 4]

In [38]:
A[5:]  #last five

[5, 6, 7, 8, 9, 10]

In [39]:
A[:5:-1] #negative slicing

[10, 9, 8, 7, 6]

In [40]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])



In [41]:
matrix[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
matrix[: ,1] #[rows ,column]

array([2, 5, 8])

In [43]:
matrix[:, ::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [44]:
new_matrix=matrix.copy()
new_matrix[:, 1] = 0
new_matrix

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])

# **Day 2**

### **Chaning array Type**

In [45]:
# i:integer -- b:boolean -- f:float -- O:object -- S:string -- U:unicode -- c:complex -- M:dateTime
arrS=np.array(["books","notebooks","pens","rubber"])
print(len("notebooks"))
arrS.dtype # U :Unincode string the latgest number of characters in word in this array is 9 letters "notebooks"


9


dtype('<U9')

In [46]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr1.astype("S")

array([b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'10'],
      dtype='|S11')

In [48]:
arr=np.array([1,2,5,6,8,4,5],dtype="U")
arr

array(['1', '2', '5', '6', '8', '4', '5'], dtype='<U1')

### **CREATION OF ARRAY**

In [49]:
# By using array
np.array(["A","B","C"])


array(['A', 'B', 'C'], dtype='<U1')

In [50]:
# By using arange
np.arange(10)
np.arange(5,11,0.5,dtype=float)


array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ,
       10.5])

In [51]:
# By using np.linespace()
np.linspace(5,10,11)#end is inclusive


array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [52]:
#identity matrix usning np.eye
np.eye(5) #it can take n,m n is no of coulmns m is no of rows

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
#np.diag has two function 
# 1-creating a array with diagonal 
np.diag([1,1,1])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [54]:
# 2- knowing the diagonal 
print(matrix)
np.diag(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 5, 9])

In [55]:
# Creating by np.zeros
print(np.zeros(5))
print("-"*70)
print(np.zeros((3,2)))
print("-"*70)
print(np.zeros((2,3,2)))

[0. 0. 0. 0. 0.]
----------------------------------------------------------------------
[[0. 0.]
 [0. 0.]
 [0. 0.]]
----------------------------------------------------------------------
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [56]:
#np.ones the same as zeros
np.ones(5)

array([1., 1., 1., 1., 1.])

## **Copy && View**
- The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array
- The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy and vise versa with View

In [57]:
A=np.array([1,2,3,4,5])
A_copy=A.copy()
A_view=A.view()

In [58]:
print(A_copy.base)#it print none if its own data
print(A_view.base)# and print the original data if its not owned data

None
[1 2 3 4 5]


In [59]:
A[0]=0
print(A_copy)
print(A_view)
print(A_view.base)

[1 2 3 4 5]
[0 2 3 4 5]
[0 2 3 4 5]


## **Shape && Reshape**

In [60]:
arr2.shape # 2 rows and 4 columns

(2, 4)

In [61]:
arr2.shape[0]#rows

2

In [62]:
arr2.shape[1]#columns

4

In [63]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr1.reshape((2,5))#it 10 items = 2*5=10

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [65]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
arr2.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# **To Be Continue... I have Exam🏃‍♂️💨**